<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCxtKxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCxtKxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRCxtKxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRCxtKxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRCxtKxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'RCxtKxC',
    'container.build_id' => '158c49c5',
    'container.build_time' => 1718536545,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCxtKxC');
